alias ls='exa'
alias cat='bat'
alias du='dust'
alias cd='z'

alias c='clear'
alias ll='ls -alFh'
alias la='ls -AF'
alias l='ls -CF'
alias df='df -h'
alias fastping='ping -i.2'
alias h='history'
alias j='jobs'
alias now='date +"%Y-%m-%d %T"'
alias nowd='date +"%Y-%m-%d"'
alias nowt='date +"%T"'
alias path='echo -e ${PATH//:/\\n}'
alias ports='netstat -tulanp'
alias su='sudo -i'
alias x='exit'

