"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username$hostname\
[](bg:#304C60 fg:#23557A)\
$directory\
[](fg:#304C60 bg:#A02070)\
$git_branch\
$git_status\
[](fg:#A02070 bg:#502050)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#502050 bg:#305050)\
$docker_context\
[ ](fg:#305050 bg:#33658A)\
$cmd_duration\
[ ](fg:#33658A)\n\
[$character](bg:none)\
[ ](fg:#23557A)\
"""

continuation_prompt = "[ »»» ](fg:#F0F070)"

scan_timeout = 100
command_timeout = 8000

# Disable the blank line at the start of the prompt
add_newline = false

[character]
#success_symbol = "[➜](bold green)"
format = '[ $symbol ](bg:#23557A)'
success_symbol = "[\\$](bold fg:#40F020 bg:#23557A)"
error_symbol = "[\\$](bold fg:#F04020 bg:#23557A)"

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#e7e7e7 bg:#23557A"
style_root = "fg:#e7e7e7 bg:#23557A"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
style = "fg:#e7e7e7 bg:#23557A"
format = '[$ssh_symbol$hostname ]($style)'

[directory]
style = "fg:#e7e7e7 bg:#304C60"
format = "[ $path ]($style)"
truncation_length = 7
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"/" = " 〉"
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#e7e7e7 bg:#305050"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#e7e7e7 bg:#A02070"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:#e7e7e7 bg:#A02070"
conflicted = " $count="
staged = " $count+"
deleted = " $count✘"
renamed = " $count»"
modified = " $count!"
untracked = " $count?"
stashed = " $count"
format = '[$conflicted$staged$deleted$renamed$modified$untracked$stashed]($style)[ $ahead_behind ](fg:#000000 bg:#A02070)'
ahead = "￪${count}"
diverged = "￪${ahead_count} ￬${behind_count}"
behind = "￬${count}"

[golang]
symbol = " "
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol ($version) ]($style)'

[rust]
#symbol = ""
style = "fg:#e7e7e7 bg:#502050"
format = '[ $symbol($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[$time ]($style)'

[cmd_duration]
style = "fg:#e7e7e7 bg:#33658A"
min_time = 2
format = '[$duration ]($style)'

