[pyprland]
plugins = ["wallpapers"]

[wallpapers]
unique = true
path = "~/Pictures/wallpapers/"
online_ratio = 1
online_backends = ["wallhaven"]
online_keywards = ["dark"]
interval = 60
recurse = true
clear_command = "awww clear"
command = "awww img '[file]' --transition-fps 255 --transition-type outer --transition-duration 0.8"
