# Nvidia hack
force_xinerama yes

# Monitors
set $monitor1 "xinerama-0"
set $monitor2 "xinerama-1"

# List of all used workspaces
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

set $ws11 "11"
set $ws12 "12"
set $ws13 "13"
set $ws14 "14"
set $ws15 "15"
set $ws16 "16"
set $ws17 "17"
set $ws18 "18"
set $ws19 "19"
set $ws20 "20"

# Assign workspaces to monitors
workspace $ws1 output $monitor1
workspace $ws2 output $monitor1
workspace $ws3 output $monitor1
workspace $ws4 output $monitor1
workspace $ws5 output $monitor1
workspace $ws6 output $monitor1
workspace $ws7 output $monitor1
workspace $ws8 output $monitor1
workspace $ws9 output $monitor1
workspace $ws10 output $monitor1

workspace $ws11 output $monitor2
workspace $ws12 output $monitor2
workspace $ws13 output $monitor2
workspace $ws14 output $monitor2
workspace $ws15 output $monitor2
workspace $ws16 output $monitor2
workspace $ws17 output $monitor2
workspace $ws18 output $monitor2
workspace $ws19 output $monitor2
workspace $ws20 output $monitor2

# Switch to workspace
bindsym $sup+F1 workspace $ws1
bindsym $sup+F2 workspace $ws2
bindsym $sup+F3 workspace $ws3
bindsym $sup+F4 workspace $ws4
bindsym $sup+F5 workspace $ws5
bindsym $sup+F6 workspace $ws6
bindsym $sup+F7 workspace $ws7
bindsym $sup+F8 workspace $ws8
bindsym $sup+F9 workspace $ws9
bindsym $sup+F10 workspace $ws10

bindsym $sup+F11 workspace $ws11
bindsym $sup+F12 workspace $ws12

# Move focused container to workspace
bindsym $sup+Shift+F1 move container to workspace $ws1
bindsym $sup+Shift+F2 move container to workspace $ws2
bindsym $sup+Shift+F3 move container to workspace $ws3
bindsym $sup+Shift+F4 move container to workspace $ws4
bindsym $sup+Shift+F5 move container to workspace $ws5
bindsym $sup+Shift+F6 move container to workspace $ws6
bindsym $sup+Shift+F7 move container to workspace $ws7
bindsym $sup+Shift+F8 move container to workspace $ws8
bindsym $sup+Shift+F9 move container to workspace $ws9
bindsym $sup+Shift+F10 move container to workspace $ws10

bindsym $sup+Shift+F11 move container to workspace $ws11
bindsym $sup+Shift+F12 move container to workspace $ws12

